version: '3'
services:
  joystick-client:
    image: ghcr.com/diegoquintanav/joystick-client:latest
    build:
      context: .
      dockerfile: docker/joystick-client/Dockerfile
    environment:
      - SERVER_PORT=9080
      - SERVER_HOST=ws://ip-sompics-server
      - SERVER_ENDPOINT=/
      - CLIENT_HOST=0.0.0.0
      - CLIENT_NAME=marta
    ports:
      - 8090:8081